### ISSUE TITLE
[Autumn Theme] some icons are white

### ISSUE THREAD

**Issue by coldsmirk** [codigrate/jetbrains-themes#3] opened 2024-01-30 02:02 UTC
Autumn is a great theme, thank you for your work on it.

I encountered an experience issue. Here is a screenshot, enough to illustrate the problem:
<img width="1738" alt="image" src="https://github.com/codigrate/jetbrains-themes/assets/18739624/c106e38e-9db7-4508-9d9b-fd2a9fee047c">

Any good suggestions?

Env
IDEA version: IntelliJ IDEA 2023.3.3
Theme version: 1.0.10

**Comment by furknyavuz** [comment] 2024-01-30 16:36
Hi @ilxqx,
Thank you so much for your kind words!

I tried the same version of Autumn Theme in the same version of JetBrains, but I couldn't reproduce the issue. I would suggest you: First switch to another theme, then remove Autumn Theme from plugins menu, then restart JetBrains, and finally reinstall Autumn Theme.

Good luck!

**Comment by ZenShouko** [comment] 2024-04-18 11:24
I second this, working in the most up-to-date version of Rider (as of 18/04/2024), the more actions button is white and barely visible.

<img width="1036" alt="white icon bug" src="https://github.com/codigrate/jetbrains-themes/assets/114538062/0b9cf766-ea11-4b39-a541-fb5d8d313b60">

**Hovering** over the button makes it visible _enough_ though.

<img width="159" alt="hover" src="https://github.com/codigrate/jetbrains-themes/assets/114538062/69621654-83d0-42d8-8f12-3d9aa691b697">

**Additionally**, I'd tweak the colours of icons to be more vibrant. This will add a better contrast and make icons pop out more. Making the grays more dark gray (FE: search and settings) and the greens less light greeny/different shade of green (FE: run and debug).
**Or**, you could make the header dark with light icon colours (similar to the default light theme of rider). This one is up to you, but I'll leave this one here for consideration.

You said you couldn't reproduce the same issue so I'm curious to know how it is supposed to look like. Because if I look at the screenshots provided at the store page, I can clearly see the more options button being white and barely visible.

<img width="770" alt="storepage" src="https://github.com/codigrate/jetbrains-themes/assets/114538062/3b4330d3-505e-40b0-88d5-48f118967f50">

**Comment by furknyavuz** [comment] 2024-04-19 18:24
Hi @ZenShouko,
Thank you for explaining further, it helped me to understood the real problem.
This issue will be fixed with the next update!

**Closed as completed** 2024-04-19 19:33 UTC
Labels: bug

**Comment by ZenShouko** [comment] 2024-04-20 18:07
Hello @furknyavuz ,
I am happy to help. Keep up the good work. Your Autumn theme is genuinely one of the best light themes out there!
